import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { ThemeProvider } from "../components/themeProvider";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/toaster"
import { CartProvider } from '@/app/context/cart-context'

export const metadata = {
  title: "Game Vault - All of your games in one place!",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" suppressHydrationWarning>
      <head/>
        <body className={inter.className}>
      <ThemeProvider defaultTheme="light">
        <CartProvider>
          <div className="relative">
            <nav className="px-5 md:px-20 lg:px-40 2xl:px-60">
              <Navbar />
            </nav>
            {children}
            <Footer />
          </div>
          </CartProvider>
      </ThemeProvider>
      <Toaster />
        </body>
    </html>
  );
}